#!/bin/bash
# shutdownscript stops all the services on the container required to
# run the lab for the safe dissembling of the lab
# Usage of the Script
# To use shutdown, run the command
# ./scripts/shutdown
# stops the Apache service
service apache2 stop
