#!/bin/bash
# start script starts all the services on the container required to
# run the lab 

# Usage of the Script 

# To use star, run the command
# ./scripts/start

# starts the Apache service
service apache2 start

