#!/bin/bash
# startup script starts all the services on the container required to
# run the lab
# Usage of the Script
# To use starup, run the command
# ./scripts/startup
# starts the Apache service
service apache2 start
